# Go library shared by both frontend and chunk.
package(default_visibility = ["//visibility:public"])

filegroup(
    name = "lib",
    srcs = [
        "auth.go",
        "constants.go",
        "ds_schema.go",
        "vector.go",
    ],
)
